<?php

namespace srag\Plugins\OnlyOffice\ObjectSettings;

use ilOnlyOfficePlugin;
use ilCheckboxInputGUI;
use ilObjOnlyOffice;
use ilObjOnlyOfficeGUI;
use ilTextAreaInputGUI;
use ilTextInputGUI;
use srag\CustomInputGUIs\OnlyOffice\PropertyFormGUI\Items\Items;
use srag\CustomInputGUIs\OnlyOffice\PropertyFormGUI\PropertyFormGUI;

/**
 * Class ObjectSettingsFormGUI
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\OnlyOffice\ObjectSettings
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ObjectSettingsFormGUI extends PropertyFormGUI
{

    const PLUGIN_CLASS_NAME = ilOnlyOfficePlugin::class;
    const LANG_MODULE = ilObjOnlyOfficeGUI::LANG_MODULE_SETTINGS;
    /**
     * @var ilObjOnlyOffice
     */
    protected $object;


    /**
     * ObjectSettingsFormGUI constructor
     *
     * @param ilObjOnlyOfficeGUI $parent
     * @param ilObjOnlyOffice    $object
     */
    public function __construct(ilObjOnlyOfficeGUI $parent, ilObjOnlyOffice $object)
    {
        $this->object = $object;

        parent::__construct($parent, $object);
    }


    /**
     * @inheritDoc
     */
    protected function getValue(string $key)
    {
        switch ($key) {
            case "description":
                return Items::getter($this->object, "long_description");

            default:
                return Items::getter($this->object, $key);
        }
    }


    /**
     * @inheritDoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilObjOnlyOfficeGUI::CMD_SETTINGS_STORE, self::plugin()->translate("save", self::LANG_MODULE));

        $this->addCommandButton(ilObjOnlyOfficeGUI::CMD_MANAGE_CONTENTS, self::plugin()->translate("cancel", self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            "title"       => [
                self::PROPERTY_CLASS    => ilTextInputGUI::class,
                self::PROPERTY_REQUIRED => true
            ],
            "description" => [
                self::PROPERTY_CLASS    => ilTextAreaInputGUI::class,
                self::PROPERTY_REQUIRED => false
            ],
            "online"      => [
                self::PROPERTY_CLASS => ilCheckboxInputGUI::class
            ],
            "open" => [
                self::PROPERTY_CLASS => \ilRadioGroupInputGUI::class,
                self::PROPERTY_REQUIRED => true,
                self::PROPERTY_SUBITEMS => [
                    [
                        self::PROPERTY_CLASS => \ilRadioOption::class,
                        self::PROPERTY_VALUE => "ilias"
                    ],
                    [
                        self::PROPERTY_CLASS => \ilRadioOption::class,
                        self::PROPERTY_VALUE => "editor"
                    ],
                    [
                        self::PROPERTY_CLASS => \ilRadioOption::class,
                        self::PROPERTY_VALUE => "download"
                    ]
                ]
            ]
        ];
    }


    /**
     * @inheritDoc
     */
    protected function initId()/*: void*/
    {

    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle(self::plugin()->translate("settings", self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function storeValue(string $key, $value)/*: void*/
    {
        switch ($key) {
            default:
                Items::setter($this->object, $key, $value);
                break;
        }
    }


    /**
     * @inheritDoc
     */
    public function storeForm() : bool
    {
        if (!parent::storeForm()) {
            return false;
        }

        $this->object->update();

        return true;
    }
}
