<?php

namespace srag\Plugins\OnlyOffice\ObjectSettings;

use ilDateTime;
use srag\Plugins\OnlyOffice\Utils\OnlyOfficeTrait;
use ActiveRecord;
use arConnector;
use ilOnlyOfficePlugin;
use srag\DIC\OnlyOffice\DICTrait;

/**
 * Class ObjectSettings
 * Generated by SrPluginGenerator v1.3.4
 * @author  Theodor Truffer <thoe@fluxlabs.ch>
 * @author  Sophie Pfister <sophie@fluxlabs.ch>
 */
class ObjectSettings extends ActiveRecord
{

    use DICTrait;
    use OnlyOfficeTrait;

    const TABLE_NAME = "rep_robj_xono_set";
    const PLUGIN_CLASS_NAME = ilOnlyOfficePlugin::class;

    /**
     * @inheritDoc
     */
    public function getConnectorContainerName() : string
    {
        return self::TABLE_NAME;
    }

    /**
     * @inheritDoc
     * @deprecated
     */
    public static function returnDbTableName() : string
    {
        return self::TABLE_NAME;
    }

    /**
     * @var int
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       8
     * @con_is_notnull   true
     * @con_is_primary   true
     */
    protected $obj_id;

    /**
     * @var string
     * @con_has_field  true
     * @con_fieldtype  text
     * @con_is_notnull true
     */
    protected $title;

    /**
     * @var string
     * @con_has_field true
     * @con_fieldtype text
     */
    protected $desc;

    /**
     * @var bool
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       1
     * @con_is_notnull   true
     */
    protected $is_online = false;

    /**
     * @var string
     * @con_has_field  true
     * @con_fieldtype  text
     * @con_length     10
     * @con_is_notnull true
     */
    protected $open_setting = "ilias";

    /**
     * @var bool
     * Indicates whether all users are allowed to edit or not
     * @con_has_field  true
     * @con_fieldtype  integer
     * @con_length     1
     * @con_is_notnull true
     */
    protected $allow_edit;

    /**
     * @var ilDateTime
     * @db_has_field         true
     * @db_fieldtype         timestamp
     */
    protected $start_time;

    /**
     * @var ilDateTime
     * @db_has_field         true
     * @db_fieldtype         timestamp
     */
    protected $end_time;

    /**
     * @var bool
     * @con_has_field  true
     * @con_fieldtype  integer
     * @con_length     1
     */
    protected $limited_period;

    /**
     * ObjectSettings constructor
     * @param int              $primary_key_value
     * @param arConnector|null $connector
     */
    public function __construct(/*int*/ $primary_key_value = 0, arConnector $connector = null)
    {
        parent::__construct($primary_key_value, $connector);
    }

    /**
     * @inheritDoc
     */
    public function sleep(/*string*/ $field_name)
    {
        $field_value = $this->{$field_name};

        switch ($field_name) {
            case "is_online":
            case "allow_edit":
                return ($field_value ? 1 : 0);
            default:
                return null;
        }
    }

    /**
     * @inheritDoc
     */
    public function wakeUp(/*string*/ $field_name, $field_value)
    {
        switch ($field_name) {
            case "obj_id":
                return intval($field_value);
            case "is_online":
            case "allow_edit":
                return boolval($field_value);
            default:
                return null;
        }
    }

    /**
     * @return int
     */
    public function getObjId() : int
    {
        return $this->obj_id;
    }

    /**
     * @param int $obj_id
     */
    public function setObjId(int $obj_id)/*: void*/
    {
        $this->obj_id = $obj_id;
    }

    public function getTitle() : string
    {
        return $this->title;
    }

    public function setTitle(string $title)
    {
        $this->title = $title;
    }

    public function getDescription() : string
    {
        return $this->desc;
    }

    public function setDescription(string $description)
    {
        $this->desc = $description;
    }

    public function allowEdit(): bool {
        return $this->allow_edit;
    }

    public function setAllowEdit(bool $allow_edit) {
        $this->allow_edit = $allow_edit;
    }

    /**
     * @return bool
     */
    public function isOnline() : bool
    {
        return $this->is_online;
    }

    /**
     * @param bool $is_online
     */
    public function setOnline(bool $is_online = true)/*: void*/
    {
        $this->is_online = $is_online;
    }

    public function getOpen() : string
    {
        return $this->open_setting;
    }

    public function setOpen(string $open)
    {
        $this->open_setting = $open;
    }

    /**
     * @return string
     */
    public function getStartTime() : ?string
    {
        return $this->start_time;
    }

    /**
     * @param ilDateTime $start_time
     */
    public function setStartTime(ilDateTime $start_time)
    {
        $this->start_time = $start_time;
    }

    /**
     * @return string
     */
    public function getEndTime() : ?string
    {
        return $this->end_time;
    }

    /**
     * @param ilDateTime $end_time
     */
    public function setEndTime(ilDateTime $end_time)
    {
        $this->end_time = $end_time;
    }

    /**
     * @return bool
     */
    public function isLimitedPeriod() : ?bool
    {
        return $this->limited_period;
    }

    /**
     * @param bool $limited_period
     */
    public function setLimitedPeriod(bool $limited_period)
    {
        $this->limited_period = $limited_period;
    }
}
