<?php

namespace srag\Plugins\OnlyOffice\Config;

use srag\Plugins\OnlyOffice\Utils\OnlyOfficeTrait;
use ilOnlyOfficePlugin;
use srag\ActiveRecordConfig\OnlyOffice\Config\AbstractFactory;
use srag\ActiveRecordConfig\OnlyOffice\Config\AbstractRepository;
use srag\ActiveRecordConfig\OnlyOffice\Config\Config;

/**
 * Class Repository
 * Generated by SrPluginGenerator v1.3.4
 * @package srag\Plugins\OnlyOffice\Config
 * @author  Theodor Truffer <theo@fluxlabs.ch>
 *         Sophie Pfister <sophie@fluxlabs.ch>
 */
final class Repository extends AbstractRepository
{

    use OnlyOfficeTrait;

    const PLUGIN_CLASS_NAME = ilOnlyOfficePlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;

    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }

    /**
     * @inheritDoc
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }

    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilOnlyOfficePlugin::PLUGIN_ID . "_config";
    }

    public function hasTemplates() : bool
    {
        return $this->getValue(ConfigFormGUI::KEY_DOC_WORD) ||
            $this->getValue(ConfigFormGUI::KEY_DOC_EXCEL) ||
            $this->getValue(ConfigFormGUI::KEY_DOC_PPT);
    }

    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::KEY_ONLYOFFICE_URL => Config::TYPE_STRING,
            ConfigFormGUI::KEY_ONLYOFFICE_SECRET => Config::TYPE_STRING,
            ConfigFormGUI::KEY_NUM_VERSIONS => Config::TYPE_INTEGER,
            ConfigFormGUI::KEY_DOC_WORD => Config::TYPE_STRING,
            ConfigFormGUI::KEY_DOC_EXCEL => Config::TYPE_STRING,
            ConfigFormGUI::KEY_DOC_PPT => Config::TYPE_STRING
        ];
    }
}
