<?php

namespace srag\Plugins\OnlyOffice\Utils;

use srag\Plugins\OnlyOffice\Repository;

/**
 * Trait OnlyOfficeTrait
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\OnlyOffice\Utils
 *
 * @author Theodor Truffer <theo@fluxlabs.ch>
 */
trait OnlyOfficeTrait
{

    /**
     * @return Repository
     */
    protected static function onlyOffice() : Repository
    {
        return Repository::getInstance();
    }
}
