<?php

namespace srag\Plugins\OnlyOffice\Utils;

use srag\Plugins\OnlyOffice\Repository;

/**
 * Trait OnlyOfficeTrait
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\OnlyOffice\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait OnlyOfficeTrait
{

    /**
     * @return Repository
     */
    protected static function onlyOffice() : Repository
    {
        return Repository::getInstance();
    }
}
