<?php

require_once 'Customizing/global/plugins/Services/Repository/RepositoryObject/OnlyOffice/vendor/autoload.php';
require_once 'libs/composer/vendor/autoload.php';

use ILIAS\DI\Container;
use srag\Plugins\OnlyOffice\StorageService\StorageService;
use srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\ilDBFileVersionRepository;
use srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\ilDBFileRepository;
use srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\ilDBFileChangeRepository;
use srag\Plugins\OnlyOffice\StorageService\Infrastructure\Common\UUID;
use Matrix\Exception;

/**
 * Class xonoCallbackHandler
 * Handles the callback generated by ONLYOFFICE Docs
 * Called by save.php
 * @author Sophie Pfister <sophie@fluxlabs.ch>
 */
class xonoCallbackHandler
{

    /** @var $dic Container */
    protected $dic;
    /** @var $storage_service StorageService */
    protected $storage_service;
    /** @var $data string */
    protected $file_data;
    /** @var $uuid UUID */
    protected $uuid;
    /** @var $file_id int */
    protected $file_id;
    /** @var $editor_id int */
    protected $editor_id;
    /** @var $extension string */
    protected $file_extension;
    /** @var $changes_object string */
    protected $changes_object;
    /** @var $serverVersion string */
    protected $serverVersion;
    /** @var $change_data string */
    protected $change_data;
    /** @var $change_extension string */
    protected $change_extension;
    /** @var string $fileUrl */
    protected $fileUrl;
    /** @var string $changeUrl */
    protected $changeUrl;

    /**
     * @throws Exception if the data cannot be fetched
     */
    public function __construct(
        Container $dic,
        string $uuid,
        int $file_id,
        array $data
    ) {
        $this->dic = $dic;
        $this->uuid = new UUID($uuid);
        $this->file_id = $file_id;

        $this->fileUrl = $data["url"];
        $this->editor_id = $data["users"][0];
        $this->serverVersion = $data["history"]["serverVersion"];
        $this->changeUrl = $data["changesurl"];
        $this->changes_object = json_encode($data["history"]["changes"]);
        $this->file_extension = pathinfo($this->fileUrl, PATHINFO_EXTENSION);
        $this->change_extension = pathinfo($this->changeUrl, PATHINFO_EXTENSION);
        $this->fetchData();
        if (!$this->file_data || !$this->change_data) {
            throw new Exception("Data could not be fetched");
        }

        $this->afterConstructor();

    }

    protected function afterConstructor()/*: void*/
    {
        $this->storage_service = new StorageService(
            $this->dic,
            new ilDBFileVersionRepository(),
            new ilDBFileRepository(),
            new ilDBFileChangeRepository()
        );
    }

    public function handleCallback() : bool
    {
        try {
            // Upload the new file
            $this->storage_service->updateFileFromUpload($this->file_data, $this->file_id, $this->uuid,
                $this->editor_id,
                $this->file_extension, $this->changes_object, $this->serverVersion, $this->change_data,
                $this->change_extension);
            return true;
        } catch (Exception $e) {
            return false;
        }
    }

    /**
     * Fetch the data from ONLYOFFICE Docs
     */
    protected function fetchData()
    {
        $this->file_data = file_get_contents($this->fileUrl);
        $this->change_data = file_get_contents($this->changeUrl);
    }
}