<#1>
<?php
\srag\Plugins\OnlyOffice\Repository::getInstance()->installTables();
?>
<#2>
<?php
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
?>
