<#1>
<?php
\srag\Plugins\OnlyOffice\Repository::getInstance()->installTables();
?>
<#2>
<?php
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileVersionAR::updateDB();
?>
<#3>
<?php
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileChangeAR::updateDB();
?>
<#4>
<?php
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileAR::updateDB();
\srag\Plugins\OnlyOffice\ObjectSettings\ObjectSettings::updateDB();
\srag\Plugins\OnlyOffice\StorageService\Infrastructure\File\FileAR::updateDB();
?>
